apm-server:
  host: "0.0.0.0:8200"

logging:
  level: warning
  json: true

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: devpass

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: devpass