apm-server:
  host: "0.0.0.0:8200"
  kibana:
    enabled: true
    host: "http://kibana:5601"
    username: elastic
    password: devpass

logging:
  level: info
  json: true

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: devpass

setup.template.settings.index:
  number_of_shards: 1
  number_of_replicas: 0

