apm-server:
  host: "0.0.0.0:8200"
  kibana:
    enabled: true
    host: kibana:5601
    path: kibana
    protocol: http
    username: elastic
    password: devpass

logging:
  level: warning
  json: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: devpass
