filebeat.inputs:
  - type: container
    format: docker
    paths:
      - '/var/lib/docker/containers/*/*.log'
    stream: "all"
    json:
      keys_under_root: true
      message_key: message
      ignore_decoding_error: true
    processors:
      - script:
          lang: javascript
          id: log_level
          source: >
            function process(event) {
                var value = event.Get("level");
                if (value === null){
                  value = "INFO"
                }
                else if (value.toLowerCase() == "warn"){
                  value = "WARNING"
                }
                else if (value.toLowerCase() == "err"){
                  value = "ERROR"
                }
                event.Put("level", value.toUpperCase());
            }

logging:
  level: warning
  json: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~


output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: elastic
  password: devpass

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
setup.ilm:
  enabled: true
  policy_file: /usr/share/filebeat/filebeat_policy.json
