version: '2.4'

services:
  # ResultSample service
  alsvc_resultsample:
    image: cccs/assemblyline-service-resultsample:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # ApiVector service
#  alsvc_apivector:
#    image: cccs/alsvc_apivector:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_apivector

  # APKaye service
  alsvc_apkaye:
    image: cccs/assemblyline-service-apkaye:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Beaver service
#  alsvc_beaver:
#    image: cccs/alsvc_beaver:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_beaver

  # CFMD service
#  alsvc_cfmd:
#    image: cccs/alsvc_cfmd:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_cfmd

  # Characterize service
  alsvc_characterize:
    image: cccs/assemblyline-service-characterize:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Cleaver service
#  alsvc_cleaver:
#    image: cccs/alsvc_cleaver:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_cleaver

  # ConfigDecoder service
#  alsvc_configdecoder:
#    image: cccs/alsvc_configdecoder:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_configdecoder

  # Espresso service
  alsvc_espresso:
    image: cccs/assemblyline-service-espresso:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Extract service
  alsvc_extract:
    image: cccs/assemblyline-service-extract:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # FrankenStrings service
#  alsvc_frankenstrings:
#    image: cccs/alsvc_frankenstrings:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_frankenstrings

  # FSecure service
#  alsvc_fsecure:
#    image: cccs/alsvc_fsecure:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003/
#    working_dir: /opt/al/al_services/alsvc_fsecure

  # IPArse service
  alsvc_iparse:
    image: cccs/assemblyline-service-iparse:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Lastline service
#  alsvc_lastline:
#    image: cccs/alsvc_lastline:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_lastline

  # MetaDefender service
  alsvc_metadefender:
    image: cccs/assemblyline-service-metadefender:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # MetaPeek service
  alsvc_metapeek:
    image: cccs/assemblyline-service-metapeek:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # NSRL service
#  alsvc_nsrl:
#    image: cccs/alsvc_nsrl:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_nsrl

  # Oletools service
  alsvc_oletools:
    image: cccs/assemblyline-service-oletools:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # PDFId service
  alsvc_pdfid:
    image: cccs/assemblyline-service-pdfid:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # PeePDF service
  alsvc_peepdf:
    image: cccs/assemblyline-service-peepdf:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # PEFile service
  alsvc_pefile:
    image: cccs/assemblyline-service-pefile:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Pixaxe service
#  alsvc_pixaxe:
#    image: cccs/alsvc_pixaxe:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_pixaxe

  # Suricata service
#  alsvc_suricata:
#    image: cccs/alsvc_suricata:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_suricata

  # Swiffer service
#  alsvc_swiffer:
#    image: cccs/alsvc_swiffer:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_swiffer

  # TagCheck service
#  alsvc_tagcheck:
#    image: cccs/alsvc_tagcheck:latest
#    environment:
#      - SERVICE_API_HOST=http://al_service_server:5003
#    working_dir: /opt/al/al_services/alsvc_tagcheck

  # TorrentSlicer service
  alsvc_torrentslicer:
    image: cccs/assemblyline-service-torrentslicer:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Unpacker service
  alsvc_unpacker:
    image: cccs/assemblyline-service-unpacker:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # VirusTotalDynamic service
  alsvc_virustotal_dynamic:
    image: cccs/assemblyline-service-virustotal-dynamic:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # VirusTotalStatic service
  alsvc_virustotal_static:
    image: cccs/assemblyline-service-virustotal-static:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

  # Yara service
  alsvc_yara:
    image: cccs/assemblyline-service-yara:latest
    environment:
      - SERVICE_API_HOST=http://al_service_server:5003

networks:
  default:
    external: true
    name: svc