
image: python:3.6

options:
  max-time: 10
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - mkdir -p /etc/assemblyline/
          - mkdir -p /var/cache/assemblyline/
          - cp test/bitbucket/config.yml /etc/assemblyline
          - apt update
          - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pip install pytest-error-for-skips  # Special for the pipeline where we know none should skip
          - pytest -rsx -vv --error-for-skips
        services:
          - zookeeper
          - riak
          - redis
          - elasticsearch
          - solr

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.0.0
      memory: 768
      environment:
        "node.name": elasticsearch
        "cluster.initial_master_nodes": elasticsearch
        "cluster.name": docker-cluster
        ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        DISCOVERY_TYPE: "single-node"

    redis:
      image: redis
      memory: 256

    riak:
      image: sgaroncse/riak-kv:2.1.4
      memory: 512
      environment:
        SOLR_HEAP: '-Xms256m -Xmx256m'

    zookeeper:
      image: zookeeper
      memory: 512

    solr:
      image: solr:7.5-alpine
      memory: 768
      environment:
        ZK_HOST: 'localhost:2181'
        SOLR_JAVA_MEM: '-Xms256m -Xmx256m'
