
image: python:3.6

options:
  max-time: 10
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update
          - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
          - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - (cd test && docker-compose up)
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pip install pytest-error-for-skips  # Special for the pipeline where we know none should skip
          - pytest -rsx --error-for-skips
        services:
          - docker
