
image: python:3.6.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - while [ `curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8098/types/default/props` != "200" ]; do netstat  -natul | grep -i LISTEN && sleep 1; done
          - pytest -rsx test/test_datastore.py -k test_riak
        services:
          #- zookeeper
          - riak
          #- redis
          #- elasticsearch
          #- solr

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:6.4.2
      memory: 512
      environment:
        ES_JAVA_OPTS: '-Xms256m -Xmx256m'
        DISCOVERY_TYPE: 'single-node'
    redis:
      image: redis
      memory: 512
    riak:
      image: sgaroncse/riak-kv:2.1.4-al
      memory: 1024
      environment:
        SOLR_HEAP: '-Xms256m -Xmx256m'
    zookeeper:
      image: zookeeper
      memory: 512
    solr:
      image: solr:7.5-alpine
      memory: 512
      environment:
        ZK_HOST: 'localhost:2181'
        SOLR_JAVA_MEM: '-Xms256m -Xmx256m'
