
image: python:3.6

options:
  max-time: 10
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update
          - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pip install pytest-error-for-skips  # Special for the pipeline where we know none should skip
          - pytest -rsx --error-for-skips
        services:
          - minio
          - zookeeper
          - riak
          - redis
          - elasticsearch
          - solr

definitions:
  services:
    minio:
      image: minio/minio
      memory: 256
      environment:
        MINIO_ACCESS_KEY: al_storage_key
        MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
      ports:
        - '9000:9000'
      command: server /data
    elasticsearch:
      image: sgaroncse/elasticsearch:6.4.2
      memory: 768
      environment:
        ES_JAVA_OPTS: '-Xms256m -Xmx256m'
        DISCOVERY_TYPE: 'single-node'
    redis:
      image: redis
      memory: 256
    riak:
      image: sgaroncse/riak-kv:2.1.4
      memory: 512
      environment:
        SOLR_HEAP: '-Xms256m -Xmx256m'
    zookeeper:
      image: zookeeper
      memory: 512
    solr:
      image: solr:7.5-alpine
      memory: 768
      environment:
        ZK_HOST: 'localhost:2181'
        SOLR_JAVA_MEM: '-Xms256m -Xmx256m'
