#
# By default a pipeline is given 4G of ram.
#   - 2G elasticsearch
#   - 0.5G redis
#   - ??? pytest (probably quite small)
#

image: python:3.6.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pytest
        services:
          - elasticsearch
          - redis

definitions:
  services:
    elasticsearch:
      image: douglasscse/bitbucket_elasticsearch:6.4.2
      memory: 2048
    redis:
      image: redis
