
image: python:3.6.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pytest
        services:
          - elasticsearch

definitions:
  services:
    elasticsearch:
      image: douglasscse/bitbucket_elasticsearch:6.4.2
      memory: 2048
