
image: python:3.6.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pytest
        services:
          - zookeeper
          - redis
          - elasticsearch
          - riak
          - solr

definitions:
  services:
    elasticsearch:
      image: douglasscse/bitbucket_elasticsearch:6.4.2
      memory: 512
    redis:
      image: redis
      memory: 512
    riak:
      image: douglasscse/bitbucket_riak:2.1.4
      memory: 512
    zookeeper:
      image: zookeeper
      memory: 512
    solr:
      image: douglasscse/bitbucket_solr:7.5-alpine
      memory: 512
