
image: python:3.6

options:
  max-time: 10
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update
          - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
          - pip install -r assemblyline/requirements.txt -r test/requirements.txt
          - pytest -rsx
        services:
          - zookeeper
          - riak
          - redis
          - elasticsearch
          - solr

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:6.4.2
      memory: 512
      environment:
        ES_JAVA_OPTS: '-Xms128m -Xmx128m'
        DISCOVERY_TYPE: 'single-node'
    redis:
      image: redis
      memory: 512
    riak:
      image: sgaroncse/riak-kv:2.1.4
      memory: 512
      environment:
        SOLR_HEAP: '-Xms128m -Xmx128m'
    zookeeper:
      image: zookeeper
      memory: 512
    solr:
      image: solr:7.5-alpine
      memory: 512
      environment:
        ZK_HOST: 'localhost:2181'
        SOLR_JAVA_MEM: '-Xms128m -Xmx128m'
