version: '2.4'

services:
  # Dependancies
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: al_storage_key
      MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
    ports:
      - '9000:9000'
    command: server /data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]
      interval: 30s
      timeout: 10s
      retries: 5

  apm_server:
    image: sgaroncse/apm-server:7.4.0
    environment:
      ES_HOSTS: elasticsearch:9200
    ports:
      - '8200:8200'
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: sgaroncse/elasticsearch:7.4.0
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      DISCOVERY_TYPE: 'single-node'
    ports:
      - '9200:9200'
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/alv4/alv4/dev/depends/config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    command: filebeat -e -strict.perms=false
    depends_on:
      elasticsearch:
        condition: service_healthy

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.4.0
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/alv4/alv4/dev/depends/config/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
    command: metricbeat -e --strict.perms=false
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - '6379:6379'
      - '6380:6379'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: sgaroncse/nginx-ssl-dev:1.15.10-2
    ports:
      - '80:80'
      - '443:443'
    environment:
      - UI_HOST=172.17.0.1
      - FQDN=localhost
      - MAX_BODY_SIZE=100M
    command: /bin/bash -c "envsubst < /tmp/default.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      kibana:
        condition: service_started

networks:
  default:
    name: backend
